pipeline {

    agent any

    triggers {
        
        githubPush()

        cron('H 1 * * *')
    }

    tools {

        jdk 'JDK21'
        maven 'Maven3'
    }

    stages {

        stage('Checkout') {

            steps {

                git branch: 'main',
                    url: 'https://github.com/ttklinh1/AutoTest.git'
            }
        }

        stage('Build') {

            steps {

                sh 'mvn clean compile'
            }
        }

        stage('Run Tests UI') {

            steps {

                sh '''
                mvn clean test \
                "-DsuiteXmlFile=src/test/resources/testng.xml" \
                -Dexecution.type=remote \
                -Dgrid.url=http://selenium-hub:4444
                '''
            }
        }

        stage('Run Tests API') {

            steps {

                sh '''
                mvn clean test \
                "-DsuiteXmlFile=src/test/resources/testng-api.xml" \
                -Dexecution.type=remote \
                -Dgrid.url=http://selenium-hub:4444
                '''
            }
        }
        stage('Nightly Regression') {

            steps {

                sh '''
                mvn clean test \
                "-DsuiteXmlFile=src/test/resources/testng-api.xml" \
                -Dexecution.type=remote
                '''
            }
        }
    }

    post {

        always {

            junit '**/surefire-reports/*.xml'

            archiveArtifacts(
                artifacts: 'screenshots/**/*',
                allowEmptyArchive: true
            )

            allure(
                includeProperties: false,
                jdk: '',
                results: [[path: 'allure-results']]
            )
        }
        success {
            echo 'Automation tests completed successfully'
        }

        failure {
            echo 'Automation tests failed'
        }
    }
}