pipeline {

    agent any

    tools {

        jdk 'JDK21'
        maven 'Maven3'
    }

    stages {

        stage('Checkout') {

            steps {

                git branch: 'main',
                    url: 'https://github.com/your-org/selenium-framework.git'
            }
        }

        stage('Build') {

            steps {

                sh 'mvn clean compile'
            }
        }

        stage('Run Tests') {

            steps {

                sh '''
                mvn clean test \
                -Dbrowser=chrome \
                -Dexecution.type=remote \
                -Dgrid.url=http://localhost:4444
                '''
            }
        }
    }

    post {

        always {

            junit '**/surefire-reports/*.xml'

            archiveArtifacts(
                artifacts: 'screenshots/**/*',
                allowEmptyArchive: true
            )

            allure(
                includeProperties: false,
                jdk: '',
                results: [[path: 'allure-results']]
            )
        }
    }
}